name: Haskell Stack Project CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install OS Packages
      uses: mstksg/get-package@v1
      with:
        apt-get: libglu1-mesa-dev freeglut3-dev mesa-common-dev
    - uses: actions/checkout@v1

    - name: Setup stack
      uses: mstksg/setup-stack@v1

    - name: Install dependencies
      run: |
        set -ex
        stack --no-terminal --install-ghc test --bench --only-dependencies
        set +ex

    - name: Build
      run: |
        set -ex
        stack --no-terminal test --bench --no-run-benchmarks --haddock --no-haddock-deps
        set +ex
